name: CI/CD PIPE-LINE

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  build-image:
    name: BUILD SPRING DOCKER IMANGE
    runs-on: ubuntu-latest
    env:
      DOCKER_USER_NAME: whdnseowkd
      DOCKER_REPOSITORY_NAME: algo-mi-api

    steps:
      - uses: actions/checkout@v4
      - name: SET UP JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: CREATE PROPERTIES
        env:
          APPLICATION_PROD_PROPERTIES_CONTENT: ${{ secrets.APPLICATION_PROD_PROPERTIES_CONTENT }}
        run: echo "$APPLICATION_PROD_PROPERTIES_CONTENT" > ./src/main/resources/application-prod.properties

      - name: SETUP GRADLE
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a

      - name: BUILD WITH GRADLE WRAPPER
        run: ./gradlew build

      - name: LOGIN TO DOCKER HUB
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: CREATE UPLOAD DIRECTORY # 도커 내부에 파일마운트를위한 디렉토리 생성
        run: mkdir -p /path/to/upload/directory

      - name: TAGS FOR DOCKER
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.DOCKER_USER_NAME }}/${{ env.DOCKER_REPOSITORY_NAME }}

      - name: DOCKER IMAGE BUILD AND PUSH
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USER_NAME }}/${{ vars.DOCKER_REPOSITORY_NAME }}:dt-0.0.1 # 도커 테그 버전

  deploy-docker-image:
    needs: build-image # build-image 작업 이후에 실행
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DEPLOY TO EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              echo ACCESS SUCCESS
              ./deploy-api.sh dt-0.0.1  # 도커 테그 버전
              '
